version: "2"
services:
  eureka:
    image: netflixoss/eureka:1.3.1
    ports:
       - "8080:8080"
    environment:
       - eureka.environment=local
       - eureka.datacenter=ndc

  hellomicroservicesbd:
    image: mysql/mysql-server:5.7
    ports:
       - "3306:3306"
    environment: 
       - MYSQL_ROOT_PASSWORD=db1n5t2nc3
       - MYSQL_DATABASE=hellomicroservices
       - MYSQL_USER=matera
       - MYSQL_PASSWORD=m@t3R@5y5t3ms

  hellomicroservicesmiddle: 
    image: willianmga/hellomicroservices:hellomicroservicesmiddle
    depends_on: 
      - hellomicroservicesbd
      - eureka
    links: 
      - hellomicroservicesbd
      - eureka

  hellomicroservicesedge: 
    image: willianmga/hellomicroservices:hellomicroservicesedge
    depends_on: 
      - hellomicroservicesmiddle 
      - eureka
    links: 
      - hellomicroservicesmiddle
      - eureka
