version: "3"
services:
  hellomicroservicesmiddle: 
    image: willianmga/hellomicroservices:hellomicroservicesmiddle

  hellomicroservicesedge: 
    image: willianmga/hellomicroservices:hellomicroservicesedge
    depends_on: 
      - hellomicroservicesmiddle 
    links: 
      - hellomicroservicesmiddle
      
